config/routes.rb
Rails.application.routes.draw do
  resources :lists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'lists#index'
  get 'home/trash_em'
  get 'home/trash_all'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def trash_em
    @trash_em = List.where(:completed => true).destroy_all
    redirect_to root_url, notice: 'All marked items were successfully deleted'
  end

  def trash_all
    @trash_all = List.all.destroy_all
    redirect_to root_url, notice: 'All items were successfully deleted'
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[ show edit update destroy ]

  # GET /lists or /lists.json
  def index
    @lists = List.all
    @list = List.new
  end

  # GET /lists/1 or /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists or /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to root_url, notice: "List was successfully created." }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1 or /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to root_url, notice: "List was successfully updated." }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1 or /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: "List was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:description, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoListApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "lists/navbar" %>
    <div class='container'>
      <%= render 'lists/flash' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_flash.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form>
    <div class="mb-3">
      <label for="exampleInputEmail1" class="form-label"><%= form.label :description %></label>
      <%= form.text_field :description, class:'form-control' %>
    </div>
    <div class="mb-3 form-check">
      <input  class="form-check-input" id="exampleCheck1"><%= form.check_box :completed, class:'form-check-input' %>
      <label class="form-check-label" for="exampleCheck1"><%= form.label :completed %></label>
    </div>
    <button type="submit" class="btn btn-primary"><%= form.submit nil, class:'btn btn-primary' %></button>
  </form>

<% end %>

app/views/lists/_form_index.html.erb
<%= form_with(model: @list, local: true) do |form| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class='form-inline my-2 my-lg-0 flex'>
    <%= form.text_field :description, class:'form-control mr-sm-2 margin'%>
    <%= form.submit nil, class:'btn btn-outline-secondary my-2 my-lg-0' %>
  </div>

<% end %>

app/views/lists/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid container-navbar">
    <%= link_to "To-Do List", root_path, class:'navbar-brand' %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

      </ul>

        <%= render 'form_index' %>

    </div>
  </div>
</nav>
</br>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<table class='table table-bordered table-hover'>

  <tbody>
    <% @lists.each do |list| %>
    <% if list.completed %>
      <tr class='table-secondary'>
        <td class='completed'><%= link_to list.description, edit_list_path(list) %></td>
        <td>
          <center>
            <%= form_for(list) do |f| %>
            <%=  f.text_field :description, type: 'hidden' %>
            <%=  f.check_box :completed, :checked => false, :style => 'visibility: hidden' %>
            <%=  f.submit "Uncross", class: 'btn btn-outline-secondary btn-sm'%>
            <% end %>
          </center>
        </td>
        <td><%= link_to 'Destroy', list, class:'btn btn-outline-danger btn-sm', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% else %>
      <tr>
        <td><%= link_to list.description, edit_list_path(list) %></td>
        <td>
          <center>
            <%= form_for(list) do |f| %>
            <%=  f.text_field :description, type: 'hidden' %>
            <%=  f.check_box :completed, :checked => true, :style => 'visibility: hidden' %>
            <%=  f.submit "Cross off", class: 'btn btn-outline-secondary btn-sm'%>
            <% end %>
          </center>
        </td>
        <td><%= link_to 'Destroy', list, class:'btn btn-outline-danger btn-sm', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Delete Marked Items', home_trash_em_path, data: { confirm: 'Are you sure?' }  %> |
<%= link_to 'Delete all Items', home_trash_all_path, data: { confirm: 'Are you sure?' }  %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p>
  <strong>Description:</strong>
  <%= @list.description %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @list.completed %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>